In [ ]:

pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.3

In [ ]:
import pandas as basavaraj
kiran = basavaraj.Series([1,2,3,4,5,])
kiran

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
import pandas as pd
marks=pd.Series([85,90,75,95])
print(marks)

0    85
1    90
2    75
3    95
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
arr = np.array([10, 20, 30, 40])
s = pd.Series(arr)

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
import pandas as pd
num=[10,2,3,4,5]
s=pd.Series(num)
print(num)

[10, 2, 3, 4, 5]

In [ ]:
import pandas as pd
num=(10,2,3,4,5)
s=pd.Series(num)
print(num)

(10, 2, 3, 4, 5)

In [ ]:
import pandas as pd
student={"name":"raimanabi","cource":"python"}
s=pd.Series(student)
print(student)

{'name': 'raimanabi', 'cource': 'python'}

In [ ]:
import pandas as pd
marks = pd.Series([85,90, 75, 95, 80])
print(marks[:3])

0    85
1    90
2    75
dtype: int64

In [ ]:
import pandas as pd
demo=[1,2,3,4,5,6,7,8]
demo
new=pd.Series(demo)
new

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [ ]:
# dict to pandas Series
import pandas as pd
student={ "name":"Basavaraj",
        "reg_no":"112",
        "place":"city clg",}
student
demo= pd.Series(student)
demo
print(demo[1])
print(demo["place"])
print(demo[-2])

112
city clg
112

/tmp/ipykernel_512/532115526.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(demo[1])
/tmp/ipykernel_512/532115526.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(demo[-2])

In [ ]:
import pandas as pd
arr=[86,45,89,43,66,7,5]
data=pd.Series(arr)
data
print(data[data> 45])

0    86
2    89
4    66
dtype: int64

In [ ]:
import pandas as pd
marks=pd.Series([80,90,100])
print(marks*2)

0    160
1    180
2    200
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
arr=np.array([23,45,67])
arr +=5
arr
new=pd.Series(arr)
new
print(new*2)
print(new[new>80])
print(new.dtype)
print(new.shape)
print(new.size)
print(new.index)
print(new.values)

0     56
1    100
2    144
dtype: int64
Series([], dtype: int64)
int64
(3,)
3
RangeIndex(start=0, stop=3, step=1)
[28 50 72]

data frame
defination:a two dimnsional data structure consisting of rowa and columns,
anology:think of it as an entire exel worksheet
synthesis:a dataframe is simply a collection of pandas series glude together sharing the same index

feature:             
demension          
structure          
indexing            
exel equivalent.     
series:
one diminsional
one column
sigle index
single column.
data frame:
two diminasioanal
multiple column
rows and column
full workshop

indesting data into a dataframe:
dictionary,list of dicts,csv file,
xlsx file

In [ ]:
# data frames pgms
#1 dict to data frame
import pandas as pd
demo={"reg_no":[11,12,13,14,15],"name":["sharat","wwww","wwsssd","wss","ravi"],"age":[22,3,11,22,3],"place":["gdg","ws","ss","sss","ws"]}
print(demo)
data=pd.dataframe

{'reg_no': [11, 12, 13, 14, 15], 'name': ['sharat', 'wwww', 'wwsssd', 'wss', 'ravi'], 'age': [22, 3, 11, 22, 3], 'place': ['gdg', 'ws', 'ss', 'sss', 'ws']}

In [ ]:
# 2) csv file to dataframe
import pandas as pd
data = pd.read_csv("/content/Employee.csv")
data

   Employ id employ name employ salary   company
0        101       anita          254k       tcs
1       1014       aksta          100k   infosys
2        104   raimanabi          225k  acceture
3       1015       madhu          255k    google

In [4]:
import pandas as pd
data =pd.read_excel("/content/Teachers.xlsx")
data

    ID   name deprtmt  salry
0  101  rahul      IT  32000
1  102  anita      HR  55000
2  103   john   sales  44000
3  104  kiran      IT  77000

note:read_csv and read_exel  autimatically phase headers and align data into rows and column instantly

In [5]:
import pandas as pd
data =pd.read_excel("/content/Teachers.xlsx")
data

    ID   name deprtmt  salry
0  101  rahul      IT  32000
1  102  anita      HR  55000
2  103   john   sales  44000
3  104  kiran      IT  77000

In [7]:
import pandas as pd
data=pd.read_csv("/content/Employee.csv")
data

   Employ id employ name employ salary   company
0        101       anita          254k       tcs
1       1014       aksta          100k   infosys
2        104   raimanabi          225k  acceture
3       1015       madhu          255k    google

In [18]:
data[["company","Employ id"]]

    company  Employ id
0       tcs        101
1   infosys       1014
2  acceture        104
3    google       1015

In [13]:
data["Employ id"]

0     101
1    1014
2     104
3    1015
Name: Employ id, dtype: int64

In [19]:
data["Age"]=[20,34,5,43]
data.to_csv("Age",index=False)
data

   Employ id employ name employ salary   company  Age
0        101       anita          254k       tcs   20
1       1014       aksta          100k   infosys   34
2        104   raimanabi          225k  acceture    5
3       1015       madhu          255k    google   43

In [23]:
data["city"]=["gadag","annigeri","hubli","ron"]
data.to_csv("city",index=False)
data

   Employ id employ name employ salary   company  Age      city
0        101       anita          254k       tcs   20     gadag
1       1014       aksta          100k   infosys   34  annigeri
2        104   raimanabi          225k  acceture    5     hubli
3       1015       madhu          255k    google   43       ron

In [25]:
data=data.drop("Age",axis=1)
data

   Employ id employ name employ salary   company      city
0        101       anita          254k       tcs     gadag
1       1014       aksta          100k   infosys  annigeri
2        104   raimanabi          225k  acceture     hubli
3       1015       madhu          255k    google       ron

In [26]:
data=data.drop("city",axis=1)
data

   Employ id employ name employ salary   company
0        101       anita          254k       tcs
1       1014       aksta          100k   infosys
2        104   raimanabi          225k  acceture
3       1015       madhu          255k    google

what do these arguments mean?
what is axis=1?
axis=0 means  look at the rows.
axis=1 means  look at the columns.
wht is inplace =true?
without this pandas just showsyou a priwews to of the deleted column in place =true seves change permently to a your variable

In [29]:
data.columns

Index(['Employ id', 'employ name', 'employ salary', 'company'], dtype='object')

In [30]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [31]:
data.shape

(4, 4)

In [34]:
data.dtypes

Employ id         int64
employ name      object
employ salary    object
company          object
dtype: object

In [35]:
data.head()

   Employ id employ name employ salary   company
0        101       anita          254k       tcs
1       1014       aksta          100k   infosys
2        104   raimanabi          225k  acceture
3       1015       madhu          255k    google

In [36]:
data.tail()

   Employ id employ name employ salary   company
0        101       anita          254k       tcs
1       1014       aksta          100k   infosys
2        104   raimanabi          225k  acceture
3       1015       madhu          255k    google

In [37]:
data.describe()

         Employ id
count     4.000000
mean    558.500000
std     526.545028
min     101.000000
25%     103.250000
50%     559.000000
75%    1014.250000
max    1015.000000

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Employ id      4 non-null      int64
 1   employ name    4 non-null      object
 2   employ salary  4 non-null      object
 3   company        4 non-null      object
dtypes: int64(1), object(3)
memory usage: 260.0+ bytes

head( peeks at the first 5 rows of the data set.
tail()peeks at the last 5 rwus of the data set.
.info(
  the system check shows memory types usage non null counts and data types for every single column.
  .discribe()
  the magic trick genarate instance summary stataitics (count,mean,std,deviation,mean,max,quatrilise)for all numric colums

In [50]:
import pandas as pd
employee={
    'ID':[101,102,103,104],
    'Name':['Rahul','Anita','John','kiran'],
    'Department':['IT','HR','sales','IT'],
    'salary':['5000','45000','45666','22222']
}
df = pd.DataFrame(employee)
print(df)

    ID   Name Department salary
0  101  Rahul         IT   5000
1  102  Anita         HR  45000
2  103   John      sales  45666
3  104  kiran         IT  22222

In [53]:
df = pd.DataFrame(employee)
df

    ID   Name Department salary
0  101  Rahul         IT   5000
1  102  Anita         HR  45000
2  103   John      sales  45666
3  104  kiran         IT  22222

In [60]:
import pandas as pd
data =pd.read_excel("/content/4 3000.xlsx")
data

  emply id     name  Age  Gender  deprtmt  salary    city joining date
0     E101    akash   25    male       IT   77655  chenni   2007-01-12
1     E102    megha   23  female       HR   45666  madras   2007-01-13
2     E103     john   28    male  Finance   87665    mysr   2007-01-14
3     E104    kavya  240  female       IT   87666   delhi   2007-01-15
4     E105   darshi   26    male    Sales   22343   mumbi   2007-01-16
5     E106  supriya   23  female       HR   98765   gadag   2007-01-17
6     E107   darshi   27    male       IT  987654   hubli   2007-01-18
7     E108    sneha   23  female      NaN  654433  belagi   2007-01-19
8     E109    vikas   33    male  Finance  663219  belagi   2007-01-20
9     E110   raiman   19    male       IT  722222     ron   2007-01-21